### ISSUE TITLE
Each subsequent request to download a new page is not being made at proper intervals. 

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#10]
This very important requirement is not working.  The code for this is obviously flawed.  Currently each threads individually waits for the specified "politeness interval" and starts without regard for other threads.  Effectively multiple requests are sent at the same time.

**Comment by ykohata** [comment]
Each crawler-thread waits for the specified time and then starts regardless of other threads. As a result, multiple threads wait for the same period and start at almost the same time.

It's supposed that this should work like [ScheduledThreadPoolExecutor#scheduleAtFixedRate()](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledThreadPoolExecutor.html).

**CralwerThread.java**
```
public void run() {
    // wait some time for each subsequent request
    waitInterval();
    crawlerTask.setStartTime(System.currentTimeMillis());
    try {
      download(new WebRequest(new URL(crawlerTask.getUrl())));
    } catch (MalformedURLException e) {
      e.printStackTrace();
    }
  }
```
