### ISSUE TITLE
The max_depth parameter should configurable on per web_site basis instead of global

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#11]
Currently the max_depth parameter is set in the application configuration file.  This should be moved to the web_site table so it can be different for each website.

**Comment by ykohata** [comment]
agreed.
let's add the following column in `web_sites` table and have the crawler read it when it starts.
```
 `max_depth` SMALLINT(5) UNSIGNED NULL DEFAULT '0',
```
