### ISSUE TITLE
[CalctrService]  CTR calculation logic is missing some specs

### ISSUE THREAD

**Issue by ykohata** [tc3-japan/website-crawler#148]
In updating CTR values in Solr documents, it seems that the current code ignores **"(old CTR + new CTR) * 0.5"** and  **"(new CTR) * 0.5"** in calculating new CTR values.
@jiangliwu - Could you confirm this?

==== spec ====

2. Update corresponding documents in the solr index.

(4) For each product_url in the result of (3), query all documents having the same product_url and update as:

If there is a record which has normalized_search_words, update its ctr field with the value of 
**(old CTR + new CTR) * 0.5**

If there's no record which has the normalized_search_words, duplicate a record in them and update and store with the normalized_search_words
**(new CTR) * 0.5**

**Comment by jiangliwu** [comment]
ok, will update
