### ISSUE TITLE
When getting some 30x response and "Location" header, code appears to also get 20X responses

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#15]
needs improvement?  this may incorrectly also catch non 204 but other 20X responses?

**Comment by ykohata** [comment]
@azhar-cograph 
The current code seems to handle response with 200 - 204.
It looks not bad to me.

** CrawlerThread.java **
```
      if (code <= 204) { // think download successful
        handlingPage(page);
      } else if (code == 304) {
        ....
        ....
```
