### ISSUE TITLE
URL Normalization code needs improvement

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#17]
[Code: Needs Improvement] currently only normalizes by removing cgid parameter which may not be the case for URL from all sites.

**Comment by ykohata** [comment]
This is the site-specific code. This needs to be removed or replaced with some declarative way. 

**Common.java**
```
  public static String normalize(String url) {
    String[] parts = url.split("&");
    return Arrays.stream(parts).filter(part -> !part.startsWith("cgid=")).collect(Collectors.joining("&"));
  }
```
