### ISSUE TITLE
Filter out URLs that have already been processed updates the page_id which maybe incorrect?

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#20]
"        // this page may already have been processed from a previous thread during the execution and should be skipped.
        // TODO: Issue - should not update page_id here
        if (destinationURL != null) {
          destinationURL.setLastModifiedAt(Date.from(Instant.now()));
          destinationURL.setPageId(finalPageId);
          destinationURLRepository.save(destinationURL);
        }"

**Comment by ykohata** [comment]
@jiangliwu (cc: @azhar-cograph )

When saving a destination URL, the current code is checking an existing record by the following.
```
DestinationURL destinationURL = destinationURLRepository.findByUrl(url);
```
This seems not good. The existing records should be searched by `url` and `page_id`.

And nothing should be done for existing records. the current code updates it as:
```
if (destinationURL != null) {
          destinationURL.setLastModifiedAt(Date.from(Instant.now()));
          destinationURL.setPageId(finalPageId);
          destinationURLRepository.save(destinationURL);
        } else {
```
No need to update `page_id` and `last_modified_at` here.


**CrawlerThread.java**
```
 if (finalPageId != null) {
        DestinationURL destinationURL = destinationURLRepository.findByUrl(url);
        // this page may already have been processed from a previous thread during the execution and should be skipped.
        if (destinationURL != null) {
          destinationURL.setLastModifiedAt(Date.from(Instant.now()));
          destinationURL.setPageId(finalPageId);
          destinationURLRepository.save(destinationURL);
        } else {
          ....
        }
....
```
