### ISSUE TITLE
In creating records in the destination_url table the URL is not being normalized

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#21]
The URL appears to be made absolute from relative but not necessarily normalized. 

Common.normalize is not used before persisiting the url.  

And this is converting relative URL to absolute URL.   
      if (url.startsWith("/")) { // relative url
        String[] part1s = homeUrl.split("//");
        String[] part2s = part1s[1].split("/");
        url = part1s[0] + "//" + part2s[0] + url;
      }
      url = Common.removeHashFromURL(url);

**Comment by ykohata** [comment]
@azhar-cograph - For destination URLs and source URLs, they don't need to be normalized even if they are product page links.
