### ISSUE TITLE
the time-limit parameter needs to be site specific so it can moved to web_site table from the confiruation file

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#23]
Each site may be specified a different time-limit.   Right there is one time-limit that needs to be changed that applies to all web_sites.

**Comment by ykohata** [comment]
Agreed.
Let's add the following column in `pages` table and let the crawler use this for crawling.
```
`crawl_time_limit`  MEDIUMINT(8) UNSIGNED NULL DEFAULT '0',
```

**Comment by jiangliwu** [comment]
@ykohata i guess this field should be added in `websites` table instead of `pages ` ?

**Comment by ykohata** [comment]
@jiangliwu - you're right. It should be `web_sites`. (modified the former post)
