### ISSUE TITLE
Another Crawler Process to detect removed pages

### ISSUE THREAD

**Issue by ykohata** [tc3-japan/website-crawler#31]
We need another version of Crawler which detects removed pages.
The new crawler is supposed to perform as:
- reads records in `pages` table, whose `deleted` is false.
- for each record, try to do a `HEAD` (or `GET`) access to get a status of the page.
  - update the `deleted` of the record with `true` if the status is `404`.
  - do nothing for other statuses.
  - no need to crawl based on links found on the page.

The main process can start this crawling process when it runs with a specific parameter e.g. `--validate-pages`. It might be good if it's possible to assign `site_id` in optional.

**Comment by azhar-cograph** [comment]
@jiangliwu  I am not sure how you are only reading in records who 'deleted' flag is false?
