### ISSUE TITLE
Moving crawler setting configuration parameters from YAML file to MySQL database tables

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#56]
1. #Interval between each subsequent request (milliseconds)
  interval: 1000

politeness interval  move to web_site table.

2.  #task parallel size
  parallel-size: 12

move to a new System table.

 3. #Timeout for downloading a page (minutes)
  timeout-download: 2

move to new System table.

 4. #Max number of times to retry a single page.
  retry-times: 2

move to new System table

5.  #Time lapse period for Expired pages in number of Days.
  page-expired-period: 30

move to web_site table.

**Comment by ykohata** [comment]
@azhar-cograph - please hold on to introduce the new system table. let's move all items to the `web_sites` table for now. thanks!

**Comment by azhar-cograph** [comment]
related pull request: https://github.com/tc3-japan/website-crawler/pull/58
