### ISSUE TITLE
No GUI message on entering invalid "Depth of Crawl", "Max Time of Crawl" or "Request Interval"

### ISSUE THREAD

**Issue by azhar-cograph** [tc3-japan/website-crawler#81]
When editing If invalid values for "Depth of Crawl", "Max Time of Crawl" or "Request Interval" such as -10 are entered for these parameters, and Save button is pressed, the incorrect values are not saved (which is correct) however user is not alerted that an incorrect value was entered.

**Comment by ykohata** [comment]
It's desirable to show proper error messages when receiving invalid input.

@azhar-cograph 
Is this an issue on the server-side (API does not return a proper response)? or frontend-side (App does not handle error responses properly)?

**Comment by azhar-cograph** [comment]
The GUI allows an invalid value to be passed to the backend.  A Hibernate DataException is thrown when executing SQL because of Table constraint violation.  This is interpreted by the REST API as an Internal server and 500 error code is returned to the client.
