### ISSUE TITLE
The copy right texts remain in the app

### ISSUE THREAD

**Issue by ykohata** [tc3-japan/website-crawler#91]
These should be removed if there's no particular reason.

@tom-co-graph - We have to show some copyright for the use of the template? Could you please confirm this?

**Comment by tom-co-graph** [comment]
The dashboard UI is released under the [MIT license](https://github.com/DashboardPack/architectui-vue-theme-free/blob/master/LICENSE).
It says that the "above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software." So it seems we maybe also need to include that whole license file? though as far as I can see this is not mentioned on the main download site: https://dashboardpack.com/theme-details/architectui-dashboard-vue-free/

Perhaps we could remove the copyright at the bottom but provide a link to the license document?
