### ISSUE TITLE
Sorter UI seems not implemented in the Site list page

### ISSUE THREAD

**Issue by ykohata** [tc3-japan/website-crawler#94]
Now it's able to change sort order by clicking column headers in the sites table.
It works but seems not user-friendly. It's desirable to provide some dedicated UI to handle it.

**Comment by azhar-cograph** [comment]
"dedicated UI"?  can you elaborate on this?

**Comment by ykohata** [comment]
@azhar-cograph sorry for this ambiguous requirements. I wanted to mean arrow icons. Please see the design doc. Thx!
