### ISSUE TITLE
Filter box should work with Description and URL

### ISSUE THREAD

**Issue by ykohata** [tc3-japan/website-crawler#98]
Now Filter in the site list page is working w/ only names of sites.
It should be working w/ Descriptions and URLs for more usability.

**Comment by tom-co-graph** [comment]
The filter box should already be filtering based on name, description and URL. Please let me know if this is not working.

**Comment by ykohata** [comment]
got it. let me confirm again. thanks!

**Comment by ykohata** [comment]
@tom-co-graph - confirmed this has been implemented properly. thanks!
